"""add: to comments_table column with ads_id

Revision ID: 0d4f8619c270
Revises: feaa217ccaeb
Create Date: 2023-08-06 12:54:45.138552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4f8619c270'
down_revision = 'feaa217ccaeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
