"""first

Revision ID: e7a7b8489018
Revises: 
Create Date: 2023-08-02 03:58:47.051810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a7b8489018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'advertisements', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_column('advertisements', 'owner_id')
    # ### end Alembic commands ###
